### ISSUE TITLE
Switch statements should have a default label

### ISSUE THREAD

**Issue by barni9606** [BME-MIT-IET/DDR4-iet-2018#8]
view/fragment/ReportFragment

**Comment by barni9606** [comment]
added default statements #10 PR

**Comment by barni9606** [comment]
more places:
firebase/FirebaseAnalyticsImpl -> trackThemeChanged
mvp/presenter/ReportPresenter -> getExpenses
view/activity/base/DrawerActivity -> setupDrawer
view/fragment/CategoryDetailsFragment -> onOptionsItemSelected
view/fragment/ExpensesDetailsFragment -> onOptionsItemSelected
view/fragment/base/BaseMvpFragment -> onOptionsItemSelected
view/fragment/base/StaticContentFragment.java -> onOptionsItemSelected
view/numpad/NumpadView -> onClick

**Comment by dim5** [comment]
#20
